syntax = "proto3";

service ModelMgmtService {
  // Requires Authorization Token in Metadata
  rpc GetModel (ModelRequest) returns (ModelResponse);
  rpc GetModels (Empty) returns (ModelsResponse);
  rpc GetModelByName (ModelByNameRequest) returns (ModelResponse);
}

message ModelRequest {
  string model_id = 1;
}

message Empty {}

message ModelByNameRequest {
  string name = 2;
}

message ModelResponse {
  bool found = 1;
  string json_data = 2;
}

message ModelsResponse {
  repeated ModelSummary models = 1;
}

message ModelSummary {
  string _id = 1;
  string name = 2;
  string type = 3;
  string engine = 4;
  bool deleted = 5;
}
